[project]
authors = ["Tomas Janicek <tomasjanicek221@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "mocrograd"
platforms = ["linux-aarch64", "osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
tests = "mojo run run_tests.mojo"
build_tests = "mojo build run_tests.mojo"
nelts = "mojo run get_nelts.mojo"
train_digits = "mojo run run_digits_training.mojo 10 100"


[dependencies]
max = ">=24.5.0"
scikit-learn = ">=1.5.2"
