[project]
authors = ["Tomas Janicek <tomas.janicek@redampsecurity.com>"]
channels = [
    "conda-forge",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/mojo-community",
]
description = "Add a short description here"
name = "mocrograd"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
tests = "mojo run run_tests.mojo"
build_tests = "mojo build run_tests.mojo"


[dependencies]
max = ">=24.5.0,<25"
numpy = ">=1.26.4,<2"
pytorch = ">=2.5.1,<3"
scikit-learn = ">=1.5.2,<2"
